---
version: "3.3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./custom.ini:/etc/grafana/grafana.ini
      - ./grafana-data:/var/lib/grafana/csv
#      - grafana-conf:/etc/grafana
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
#      - GF_PLUGIN_MARCUSOLSSON_CSV_DATASOURCE_ALLOW_LOCAL_MODE=true

volumes:
  grafana-data:
  grafana-conf:
